#!/usr/bin/bash
swww img ~/.local/share/Wallpapers/NordicWallpapers/wild.png

if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
	$0 ~/.local/share/Wallpapers/NordicWallpapers/
	exit 1
fi
# Edit bellow to control the images transition
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=60

# INTERVAL=500

while true; do
	find "$1" \
		| while read -r img; do
			echo "$((RANDOM % 1000)):$img"
		done \
		| sort -n | cut -d':' -f2- \
		| while read -r img; do
			swww img "$img" --transition-type any
			sleep 500
		done
done
