####################
# General settings #
####################

# "full"" backend to use all image colors, slower but better
backend = "full"

# color space "lab" for more even colors
color_space = "lab"

# Ensures a "readable contrast"
check_contrast = true

# good balance for not too similiar nor different colors
threshold = 19

# dark mode forever
filter = "darkcomp16"

# pywal
pywal = false

#############
# Templates #
#############

# Replicate pywal colors.json for compatibility
[templates]

colors-json = { template = "pywal", target = "~/.cache/wal/colors.json" }

colors = { template = "walcolors", target = "~/.cache/wal/colors" }

colors-sh = { template = "sh-colors", target = "~/.cache/wal/colors.sh" }

zathura = { template = "zathura", target = "~/.config/zathura/wallust" }

kitty = { template = "kitty", target = "~/.config/kitty/wallust.conf" }

qutebrowser = { template = "colors.json", target = "~/.config/qutebrowser/colors.json" }

tofi = { template = "tofi-colors", target = "~/.config/tofi/colors" }

eww = { template = "eww-scss", target = "~/.config/eww/_colors.scss" }
