# $wallpaper_path= ~/.local/share/Wallpapers/Misc/mountains.png
# $wallpaper_path= ~/.local/share/Wallpapers/Misc/forest.png
$wallpaper_path= ~/.local/share/wallpapers/space.jpg


preload = $wallpaper_path


wallpaper = DP-1, $wallpaper_path
wallpaper = DP-2, $wallpaper_path
wallpaper = DP-3, $wallpaper_path
wallpaper = eDP-1, $wallpaper_path

# enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
