[mgr]

[[mgr.keymap]]
on = [ "<Esc>" ]
run = "escape"
desc = "Exit visual mode, clear selected, or cancel search"

[[mgr.keymap]]
on = [ "q" ]
run = "quit"
desc = "Exit the process"

[[mgr.keymap]]
on = [ "Q" ]
run = "quit --no-cwd-file"
desc = "Exit the process without writing cwd-file"

[[mgr.keymap]]
on = [ "<C-q>" ]
run = "close"
desc = "Close the current tab, or quit if it is last tab"

[[mgr.keymap]]
on = [ "<C-z>" ]
run = "suspend"
desc = "Suspend the process"

# Navigation
[[mgr.keymap]]
on = [ "l" ]
run = "arrow -1"
desc = "Move cursor up"

[[mgr.keymap]]
on = [ "k" ]
run = "arrow 1"
desc = "Move cursor down"

[[mgr.keymap]]
on = [ "<Up>" ]
run = "plugin augment-command -- parent_arrow -1"
desc = "Move up in the parent directory"

[[mgr.keymap]]
on = [ "<Down>" ]
run = "plugin augment-command -- parent_arrow 1"
desc = "Move down in the parent directory"

[[mgr.keymap]]
on = [ "<S-Up>" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"

[[mgr.keymap]]
on = [ "<S-Down>" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

[[mgr.keymap]]
on = [ "<C-u>" ]
run = "arrow -50%"
desc = "Move cursor up half page"

[[mgr.keymap]]
on = [ "<C-d>" ]
run = "arrow 50%"
desc = "Move cursor down half page"

[[mgr.keymap]]
on = [ "<C-b>" ]
run = "arrow -100%"
desc = "Move cursor up one page"

[[mgr.keymap]]
on = [ "<C-f>" ]
run = "arrow 100%"
desc = "Move cursor down one page"

[[mgr.keymap]]
on = [ "<C-PageUp>" ]
run = "arrow -50%"
desc = "Move cursor up half page"

[[mgr.keymap]]
on = [ "<C-PageDown>" ]
run = "arrow 50%"
desc = "Move cursor down half page"

[[mgr.keymap]]
on = [ "j" ]
run = [ "leave", "escape --visual --select" ]
desc = "Go back to the parent directory"

[[mgr.keymap]]
on = [ "J" ]
run = "back"
desc = "Go back to the previous directory"

[[mgr.keymap]]
on = [ "?" ]
run = "forward"
desc = "Go forward to the next directory"

[[mgr.keymap]]
on = [ "<PageUp>" ]
run = "seek -5"
desc = "Seek up 5 units in the preview"

[[mgr.keymap]]
on = [ "<PageDown>" ]
run = "seek 5"
desc = "Seek down 5 units in the preview"

[[mgr.keymap]]
on = [ "<End>" ]
run = "arrow bot"
desc = "Move cursor to the top"

[[mgr.keymap]]
on = [ "<Home>" ]
run = "arrow top"
desc = "Move cursor to the bottom"

# Selection
[[mgr.keymap]]
on = [ "<Space>" ]
run = [ "toggle --state=none", "arrow 1" ]
desc = "Toggle the current selection state"

[[mgr.keymap]]
on = [ "v" ]
run = "visual_mode"
desc = "Enter visual mode (selection mode)"

[[mgr.keymap]]
on = [ "V" ]
run = "visual_mode --unset"
desc = "Enter visual mode (unset mode)"

[[mgr.keymap]]
on = [ "<C-a>" ]
run = "toggle_all --state=true"
desc = "Select all files"

[[mgr.keymap]]
on = [ "<C-r>" ]
run = "toggle_all --state=none"
desc = "Inverse selection of all files"

# Operation
[[mgr.keymap]]
on = [ "o" ]
run = "open"
desc = "Open the selected files"

[[mgr.keymap]]
on = [ "O" ]
run = "open --interactive"
desc = "Open the selected files interactively"

[[mgr.keymap]]
on = [ "e" ]
run = """
shell  --block --confirm 'emacsclient -t "$@"'
"""
desc = "Open the selected files"

[[mgr.keymap]]
on = [ "E" ]
run = """
shell --confirm 'emacsclient -c "$@"'
"""
desc = "Open the selected files"

[[mgr.keymap]]
on = [ "$" ]
run = """shell --confirm 'kitty -d "$(pwd)"'"""
desc = "Open kitty in current pwd"

[[mgr.keymap]]
on = [ "y" ]
run = [ "yank", "escape --visual --select" ]
desc = "Copy the selected files"

[[mgr.keymap]]
on = [ "Y" ]
run = [ "unyank", "escape --visual --select" ]
desc = "Cancel the yank status of files"

[[mgr.keymap]]
on = [ "x" ]
run = [ "yank --cut", "escape --visual --select" ]
desc = "Cut the selected files"

[[mgr.keymap]]
on = [ "p" ]
run = "paste"
desc = "Paste the files"

[[mgr.keymap]]
on = [ "P" ]
run = "paste --force"
desc = "Paste the files (overwrite if the destination exists)"

[[mgr.keymap]]
on = [ "-" ]
run = "link"
desc = "Symlink the absolute path of files"

[[mgr.keymap]]
on = [ "_" ]
run = "link --relative"
desc = "Symlink the relative path of files"

[[mgr.keymap]]
on = [ "d" ]
run = [ "remove", "escape --visual --select" ]
desc = "Move the files to the trash"

[[mgr.keymap]]
on = [ "D" ]
run = [ "remove --permanently", "escape --visual --select" ]
desc = "Permanently delete the files"

[[mgr.keymap]]
on = [ "a" ]
run = "create"
desc = "Create a file or directory (ends with / for directories)"

[[mgr.keymap]]
on = [ "A" ]
run = "create --dir"
desc = "Create a directory"

[[mgr.keymap]]
on = [ "r" ]
run = "rename --cursor=before_ext"
desc = "Rename a file or directory"

[[mgr.keymap]]
on = [ "R" ]
run = "rename --cursor=start --empty=stem"
desc = "Rename a file or directory"

[[mgr.keymap]]
on = [ ";" ]
run = "shell --interactive"
desc = "Run a shell command"

[[mgr.keymap]]
on = [ ":" ]
run = "shell --interactive --block"
desc = "Run a shell command (block the UI until the command finishes)"

[[mgr.keymap]]
on = [ "." ]
run = "hidden toggle"
desc = "Toggle the visibility of hidden files"

[[mgr.keymap]]
on = [ "s" ]
run = "search fd"
desc = "Search files by name using fd"

[[mgr.keymap]]
on = [ "S" ]
run = "search rg"
desc = "Search files by content using ripgrep"

[[mgr.keymap]]
on = [ "<C-s>" ]
run = "search none"
desc = "Cancel the ongoing search"

[[mgr.keymap]]
on = [ "z" ]
run = [ "plugin zoxide" ]
desc = "Jump to a directory using zoxide"

[[mgr.keymap]]
on = [ "Z" ]
run = [ "plugin fzf" ]
desc = "Jump to a directory, or reveal a file using fzf"

# Copy
[[mgr.keymap]]
on = [ "c", "c" ]
run = "copy path"
desc = "Copy the absolute path"

[[mgr.keymap]]
on = [ "c", "d" ]
run = "copy dirname"
desc = "Copy the path of the parent directory"

[[mgr.keymap]]
on = [ "c", "f" ]
run = "copy filename"
desc = "Copy the name of the file"

[[mgr.keymap]]
on = [ "c", "n" ]
run = "copy name_without_ext"
desc = "Copy the name of the file without the extension"

# Find
[[mgr.keymap]]
on = [ "h" ]
run = "find --smart"
desc = "Find next file"

[[mgr.keymap]]
on = [ "H" ]
run = "find --previous --smart"
desc = "Find previous file"

[[mgr.keymap]]
on = [ "n" ]
run = "find_arrow"
desc = "Go to next found file"

[[mgr.keymap]]
on = [ "N" ]
run = "find_arrow --previous"
desc = "Go to previous found file"

# Sorting
[[mgr.keymap]]
on = [ ",", "m" ]
run = "sort mtime"
desc = "Sort by modified time"

[[mgr.keymap]]
on = [ ",", "M" ]
run = "sort mtime --reverse"
desc = "Sort by modified time (reverse)"

[[mgr.keymap]]
on = [ ",", "c" ]
run = "sort created --reverse=no"
desc = "Sort by created time"

[[mgr.keymap]]
on = [ ",", "C" ]
run = "sort created  --reverse"
desc = "Sort by created time (reverse)"

[[mgr.keymap]]
on = [ ",", "e" ]
run = "sort extension --reverse=no"
desc = "Sort by extension"

[[mgr.keymap]]
on = [ ",", "E" ]
run = "sort extension --reverse"
desc = "Sort by extension (reverse)"

[[mgr.keymap]]
on = [ ",", "a" ]
run = "sort alphabetical --reverse=no"
desc = "Sort alphabetically"

[[mgr.keymap]]
on = [ ",", "A" ]
run = "sort alphabetical --reverse"
desc = "Sort alphabetically (reverse)"

[[mgr.keymap]]
on = [ ",", "n" ]
run = "sort natural --reverse=no"
desc = "Sort naturally"

[[mgr.keymap]]
on = [ ",", "N" ]
run = "sort natural --reverse"
desc = "Sort naturally (reverse)"

[[mgr.keymap]]
on = [ ",", "s" ]
run = "sort size --reverse=no"
desc = "Sort by size"

[[mgr.keymap]]
on = [ ",", "S" ]
run = "sort size --reverse"
desc = "Sort by size (reverse)"

# Tabs
[[mgr.keymap]]
on = [ "t" ]
run = "tab_create --current"
desc = "Create a new tab using the current path"

[[mgr.keymap]]
on = [ "1" ]
run = "tab_switch 0"
desc = "Switch to the first tab"

[[mgr.keymap]]
on = [ "2" ]
run = "plugin smart-switch 1"
desc = "Switch to the second tab"

[[mgr.keymap]]
on = [ "3" ]
run = "plugin smart-switch 2"
desc = "Switch to the third tab"

[[mgr.keymap]]
on = [ "4" ]
run = "plugin smart-switch 3"
desc = "Switch to the fourth tab"

[[mgr.keymap]]
on = [ "5" ]
run = "plugin smart-switch 4"
desc = "Switch to the fifth tab"

[[mgr.keymap]]
on = [ "6" ]
run = "plugin smart-switch 5"
desc = "Switch to the sixth tab"

[[mgr.keymap]]
on = [ "7" ]
run = "plugin smart-switch 6"
desc = "Switch to the seventh tab"

[[mgr.keymap]]
on = [ "8" ]
run = "plugin smart-switch 7"
desc = "Switch to the eighth tab"

[[mgr.keymap]]
on = [ "9" ]
run = "plugin smart-switch 8"
desc = "Switch to the ninth tab"

[[mgr.keymap]]
on = [ "[" ]
run = "tab_switch -1 --relative"
desc = "Switch to the previous tab"

[[mgr.keymap]]
on = [ "]" ]
run = "tab_switch 1 --relative"
desc = "Switch to the next tab"

[[mgr.keymap]]
on = [ "{" ]
run = "tab_swap -1"
desc = "Swap the current tab with the previous tab"

[[mgr.keymap]]
on = [ "}" ]
run = "tab_swap 1"
desc = "Swap the current tab with the next tab"

# Tasks
[[mgr.keymap]]
on = [ "w" ]
run = "tasks_show"
desc = "Show the tasks manager"

# Goto
[[mgr.keymap]]
on = [ "g", "g" ]
run = "cd --interactive"
desc = "Go to directory interactively"

[[mgr.keymap]]
on = [ "g", "h" ]
run = "cd ~"
desc = "Go to the home directory"

[[mgr.keymap]]
on = [ "g", "c" ]
run = "cd ~/.config"
desc = "Go to the config directory"

[[mgr.keymap]]
on = [ "g", "u" ]
run = "cd $HOME/uni"
desc = "Go to the uni directory"

[[mgr.keymap]]
on = [ "g", "w" ]
run = "cd $HOME/work"
desc = "Go to the work directory"

[[mgr.keymap]]
on = [ "g", "P" ]
run = "cd $HOME/projects"
desc = "Go to the project directory"

[[mgr.keymap]]
on = [ "g", "p" ]
run = "cd $HOME/personal"
desc = "Go to the personal directory"

[[mgr.keymap]]
on = [ "g", "d" ]
run = "cd $HOME/inbox"
desc = "Go to the downloads directory"

[[mgr.keymap]]
on = [ "g", "t" ]
run = "cd /tmp"
desc = "Go to the temporary directory"

# Help
[[mgr.keymap]]
on = [ "~" ]
run = "help"
desc = "Open help"


# ---------------------------
# PREPEND KEYMAP
# ---------------------------

[[mgr.prepend_keymap]]
on = [ "/" ]
run = "plugin augment-command enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "<C-n>" ]
run = """shell 'xdragon -T -x -A "$@" & pypr hide yazi' --confirm"""
desc = ""

[[mgr.prepend_keymap]]
on = [ "<A-s>" ]
run = """shell 'python ~/GoogleDrive/Projects/MySmallProgrammingJourney/Python/LinuxScript/fast-open-directory/yazi.py ' --confirm --block"""
desc = ""

[[mgr.prepend_keymap]]
on = "b"
run = "plugin whoosh jump_by_key"
desc = "Jump bookmark by key"

# Direct fuzzy search access
[[mgr.prepend_keymap]]
on = "B"
run = "plugin whoosh jump_by_fzf"
desc = "Direct fuzzy search for bookmarks"

# Basic bookmark operations
[[mgr.prepend_keymap]]
on = [ "]", "a" ]
run = "plugin whoosh save"
desc = "Add bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "A" ]
run = "plugin whoosh save_cwd"
desc = "Add bookmark (current directory)"

# Temporary bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "t" ]
run = "plugin whoosh save_temp"
desc = "Add temporary bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "T" ]
run = "plugin whoosh save_cwd_temp"
desc = "Add temporary bookmark (current directory)"

# Jump to bookmarks
[[mgr.prepend_keymap]]
on = "<A-k>"
run = "plugin whoosh jump_key_k"
desc = "Jump directly to bookmark with key k"

[[mgr.prepend_keymap]]
on = [ "]", "f" ]
run = "plugin whoosh jump_by_fzf"
desc = "Jump bookmark by fzf"

# Delete bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "d" ]
run = "plugin whoosh delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "D" ]
run = "plugin whoosh delete_by_fzf"
desc = "Delete bookmarks by fzf (use TAB to select multiple)"

[[mgr.prepend_keymap]]
on = [ "]", "C" ]
run = "plugin whoosh delete_all"
desc = "Delete all user bookmarks"

# Rename bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "r" ]
run = "plugin whoosh rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "R" ]
run = "plugin whoosh rename_by_fzf"
desc = "Rename bookmark by fzf"


# work tools
[[mgr.prepend_keymap]]
on = [ "u", "u", "o" ]
run = """shell 'python ~/move_to_obsolete.py "$@"' --confirm --block"""
desc = "move to obsolete"

# chmod plugin
[[mgr.prepend_keymap]]
on = [ "c", "m" ]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = [ "<A-d>" ]
run = "plugin diff"
desc = "Diff the selected with the hovered file"

# archive plugin
[[mgr.prepend_keymap]]
on = [ "c", "a" ]
run = "plugin compress"
desc = "Archive selected files"

# smart-filter plugin
[[mgr.prepend_keymap]]
on = [ "f" ]
run = "filter --smart"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = [ "T" ]
run = "plugin --sync max-preview"
desc = "Maximize or restore preview"


[tasks]

[[tasks.keymap]]
on = [ "<Esc>" ]
run = "close"
desc = "Hide the task manager"

[[tasks.keymap]]
on = [ "q" ]
run = "close"
desc = "Hide the task manager"

[[tasks.keymap]]
on = [ "l" ]
run = "arrow -1"
desc = "Move cursor up"

[[tasks.keymap]]
on = [ "k" ]
run = "arrow 1"
desc = "Move cursor down"

[[tasks.keymap]]
on = [ "<Enter>" ]
run = "inspect"
desc = "Inspect the task"

[[tasks.keymap]]
on = [ "x" ]
run = "cancel"
desc = "Cancel the task"

[[tasks.keymap]]
on = [ "~" ]
run = "help"
desc = "Open help"


[select]

[[select.keymap]]
on = [ "<C-q>" ]
run = "close"
desc = "Cancel selection"

[[select.keymap]]
on = [ "<Esc>" ]
run = "close"
desc = "Cancel selection"

[[select.keymap]]
on = [ "<Enter>" ]
run = "close --submit"
desc = "Submit the selection"

[[select.keymap]]
on = [ "l" ]
run = "arrow -1"
desc = "Move cursor up"

[[select.keymap]]
on = [ "k" ]
run = "arrow 1"
desc = "Move cursor down"

[[select.keymap]]
on = [ "l" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"

[[select.keymap]]
on = [ "k" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

[[select.keymap]]
on = [ "~" ]
run = "help"
desc = "Open help"


[input]

[[input.keymap]]
on = [ "<C-q>" ]
run = "close"
desc = "Cancel input"

[[input.keymap]]
on = [ "<Enter>" ]
run = "close --submit"
desc = "Submit the input"

[[input.keymap]]
on = [ "<Esc>" ]
run = "escape"
desc = "Go back the normal mode, or cancel input"

# Mode
[[input.keymap]]
on = [ "i" ]
run = "insert"
desc = "Enter insert mode"

[[input.keymap]]
on = [ "a" ]
run = "insert --append"
desc = "Enter append mode"

[[input.keymap]]
on = [ "I" ]
run = [ "move -999", "insert" ]
desc = "Move to the BOL, and enter insert mode"

[[input.keymap]]
on = [ "A" ]
run = [ "move 999", "insert --append" ]
desc = "Move to the EOL, and enter append mode"

[[input.keymap]]
on = [ "v" ]
run = "visual"
desc = "Enter visual mode"

[[input.keymap]]
on = [ "V" ]
run = [ "move -999", "visual", "move 999" ]
desc = "Enter visual mode and select all"

# Character-wise movement
[[input.keymap]]
on = [ "h" ]
run = "move -1"
desc = "Move back a character"

[[input.keymap]]
on = [ "l" ]
run = "move 1"
desc = "Move forward a character"

[[input.keymap]]
on = [ "<Left>" ]
run = "move -1"
desc = "Move back a character"

[[input.keymap]]
on = [ "<Right>" ]
run = "move 1"
desc = "Move forward a character"

[[input.keymap]]
on = [ "<C-b>" ]
run = "move -1"
desc = "Move back a character"

[[input.keymap]]
on = [ "<C-f>" ]
run = "move 1"
desc = "Move forward a character"

# Word-wise movement
[[input.keymap]]
on = [ "b" ]
run = "backward"
desc = "Move back to the start of the current or previous word"

[[input.keymap]]
on = [ "w" ]
run = "forward"
desc = "Move forward to the start of the next word"

[[input.keymap]]
on = [ "e" ]
run = "forward --end-of-word"
desc = "Move forward to the end of the current or next word"

[[input.keymap]]
on = [ "<A-b>" ]
run = "backward"
desc = "Move back to the start of the current or previous word"

[[input.keymap]]
on = [ "<A-f>" ]
run = "forward --end-of-word"
desc = "Move forward to the end of the current or next word"

# Line-wise movement
[[input.keymap]]
on = [ "0" ]
run = "move -999"
desc = "Move to the BOL"

[[input.keymap]]
on = [ "$" ]
run = "move 999"
desc = "Move to the EOL"

[[input.keymap]]
on = [ "<C-a>" ]
run = "move -999"
desc = "Move to the BOL"

[[input.keymap]]
on = [ "<C-e>" ]
run = "move 999"
desc = "Move to the EOL"

[[input.keymap]]
on = [ "<Home>" ]
run = "move -999"
desc = "Move to the BOL"

[[input.keymap]]
on = [ "<End>" ]
run = "move 999"
desc = "Move to the EOL"

# Delete
[[input.keymap]]
on = [ "<C-h>" ]
run = "backspace"
desc = "Delete the character before the cursor"

[[input.keymap]]
on = [ "<C-d>" ]
run = "backspace --under"
desc = "Delete the character under the cursor"

[[input.keymap]]
on = [ "<Backspace>" ]
run = "backspace"
desc = "Delete the character before the cursor"

[[input.keymap]]
on = [ "<Delete>" ]
run = "backspace --under"
desc = "Delete the character under the cursor"

# Kill
[[input.keymap]]
on = [ "<C-u>" ]
run = "kill bol"
desc = "Kill backwards to the BOL"

[[input.keymap]]
on = [ "<C-k>" ]
run = "kill eol"
desc = "Kill forwards to the EOL"

[[input.keymap]]
on = [ "<C-w>" ]
run = "kill backward"
desc = "Kill backwards to the start of the current word"

[[input.keymap]]
on = [ "<A-d>" ]
run = "kill forward"
desc = "Kill forwards to the end of the current word"

# Cut/Yank/Paste
[[input.keymap]]
on = [ "d" ]
run = "delete --cut"
desc = "Cut the selected characters"

[[input.keymap]]
on = [ "D" ]
run = [ "delete --cut", "move 999" ]
desc = "Cut until the EOL"

[[input.keymap]]
on = [ "c" ]
run = "delete --cut --insert"
desc = "Cut the selected characters, and enter insert mode"

[[input.keymap]]
on = [ "C" ]
run = [ "delete --cut --insert", "move 999" ]
desc = "Cut until the EOL, and enter insert mode"

[[input.keymap]]
on = [ "x" ]
run = [ "delete --cut", "move 1 --in-operating" ]
desc = "Cut the current character"

[[input.keymap]]
on = [ "y" ]
run = "yank"
desc = "Copy the selected characters"

[[input.keymap]]
on = [ "p" ]
run = "paste"
desc = "Paste the copied characters after the cursor"

[[input.keymap]]
on = [ "P" ]
run = "paste --before"
desc = "Paste the copied characters before the cursor"

# Undo/Redo
[[input.keymap]]
on = [ "u" ]
run = "undo"
desc = "Undo the last operation"

[[input.keymap]]
on = [ "<C-r>" ]
run = "redo"
desc = "Redo the last operation"

# Help
[[input.keymap]]
on = [ "~" ]
run = "help"
desc = "Open help"


[completion]

[[completion.keymap]]
on = [ "<C-q>" ]
run = "close"
desc = "Cancel completion"

[[completion.keymap]]
on = [ "<Tab>" ]
run = "close --submit"
desc = "Submit the completion"

[[completion.keymap]]
on = [ "<Enter>" ]
run = [ "close --submit", "close_input --submit" ]
desc = "Submit the completion and input"

[[completion.keymap]]
on = [ "<A-k>" ]
run = "arrow -1"
desc = "Move cursor up"

[[completion.keymap]]
on = [ "<A-j>" ]
run = "arrow 1"
desc = "Move cursor down"

[[completion.keymap]]
on = [ "<Up>" ]
run = "arrow -1"
desc = "Move cursor up"

[[completion.keymap]]
on = [ "<Down>" ]
run = "arrow 1"
desc = "Move cursor down"

[[completion.keymap]]
on = [ "~" ]
run = "help"
desc = "Open help"


[help]

[[help.keymap]]
on = [ "<Esc>" ]
run = "escape"
desc = "Clear the filter, or hide the help"

[[help.keymap]]
on = [ "q" ]
run = "close"
desc = "Exit the process"

[[help.keymap]]
on = [ "<C-q>" ]
run = "close"
desc = "Hide the help"

# Navigation
[[help.keymap]]
on = [ "k" ]
run = "arrow -1"
desc = "Move cursor up"

[[help.keymap]]
on = [ "j" ]
run = "arrow 1"
desc = "Move cursor down"

[[help.keymap]]
on = [ "K" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"

[[help.keymap]]
on = [ "J" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

[[help.keymap]]
on = [ "<Up>" ]
run = "arrow -1"
desc = "Move cursor up"

[[help.keymap]]
on = [ "<Down>" ]
run = "arrow 1"
desc = "Move cursor down"

[[help.keymap]]
on = [ "<S-Up>" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"

[[help.keymap]]
on = [ "<S-Down>" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

# Filtering
[[help.keymap]]
on = [ "f" ]
run = "filter"
desc = "Apply a filter for the help items"
