matches:
  - trigger: ':d:'
    replace: '{{mydate}}'
    vars:
      - name: mydate
        type: date
        params:
          format: '%m/%d/%Y'

  - trigger: ':mail'
    replace: 'sstefanomarton@gmail.com'
