matches:
  - trigger: ':d:'
    replace: '{{mydate}}'
    vars:
      - name: mydate
        type: date
        params:
          format: '%m/%d/%Y'

  - trigger: ':mail'
    replace: 'sstefanomarton@gmail.com'

  - regex: "perche\\s"
    replace: 'perché '

  - regex: "poiche\\s"
    replace: 'poiché '

  - regex: "piu\\s"
    replace: 'più '

  - regex: "\\see\\s"
    replace: ' è '

  - regex: "^ee\\s"
    replace: 'è '

  - regex: "\\sE\\s"
    replace: ' È '

  - regex: "^E\\s"
    replace: 'È '
