matches:
  - trigger: ':d:'
    replace: '{{mydate}}'
    vars:
      - name: mydate
        type: date
        params:
          format: '%m/%d/%Y'

  - trigger: ':mail'
    replace: 'sstefanomarton@gmail.com'

  - regex: "perche\\s"
    replace: 'perché '

  - regex: "poiche\\s"
    replace: 'poiché '

  - regex: "cosee\\s"
    replace: "cos'è "

  - regex: "Cosee\\s"
    replace: "Cos'è "

  - regex: "comee\\s"
    replace: "com'è "

  - regex: "Comee\\s"
    replace: "Com'è "

  - regex: "(?P<word>\\w)aa\\s"
    replace: "{{word}}à "

  - regex: "(?P<word>\\w)oo\\s"
    replace: "{{word}}ò "

  - regex: "(?P<word>\\w)ee\\s"
    replace: "{{word}}é "

  - regex: "piu\\s"
    replace: 'più '

  - regex: "\\see\\s"
    replace: ' è '

  - regex: "^ee\\s"
    replace: 'è '

  - regex: "\\sE\\s"
    replace: ' È '

  - regex: "^E\\s"
    replace: 'È '
